### ISSUE TITLE
Some issues and test code

### ISSUE THREAD

**Issue by ky-zhou** [bednarikjan/differential_surface_representation#7]
The data downloaded from AtlasNet does not match your description, which took me some time to figure out. AtlasNet no longer provide `customShapeNet`, so I just downloaded from a [AtlasNet2](https://github.com/TheoDEPRELLE/AtlasNetV2) version. And there is also no txt file `synsetoffset2category.txt` from AtlasNet, which can be found from the data provided by [PointNet++](https://github.com/charlesq34/pointnet2).

Another thing is that there is no test code. Can you please provide it or tell me how to do so? Thank you.

**Comment by Barbany** [comment]
Any news on how to account for the missing text file @ky-zhou ? I'm trying to train the model on the textureless dataset, which is claimed to also be supported in the README. However, the config files are not provided. Could you please provide the config.yaml file @bednarikjan ?
